### ISSUE TITLE
Bug page de context

### ISSUE THREAD

**Issue by frederic1987** [zyra83/miligo#31]
Si on ne selectionne pas la borne, elle reste à null.

**Comment by zyra83** [comment]
La mise en session est effectuée quand on change la valeur des listes déroulantes.
Solution possible (facile, crade) : mettre une valeur vide par défaut sur chaque liste déroulante.
Solution possible 2 (plus long mais propre) : n'envoyer les configurations que lors de l'appuie sur le bouton d'envoi.
